# Generated by Django 5.0.7 on 2024-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='publico_alvo',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('b2g', 'B2G')], max_length=3),
        ),
    ]
